### ISSUE TITLE
Nouvelle fonction: régies publicitaires et respect de l'utilisateur

### ISSUE THREAD

**Issue by lamaeldo** [david-legrand/kimetrak#2]
Une autre idée serait (avec la communauté aussi) de spécifier à quelle régie publicitaire ces sous-domaines sont liés et instaurer un système de "drapeau" qui note la confidentialité et le respect des données des utilisateurs par ces mêmes régies publicitaires. Sinon, bravo pour cette extension et merci

**Comment by david-legrand** [comment]
Voir ma réponse sur #1 puisque les deux éléments sont liés ;) Même si l'idée d'une notation implique tout de même pas mal de choses complexes qui ne sont pas forcément simples à vérifier. Mais quand on introduira la base, on verra ce qu'il en est.
